"""Publish the extraction artefacts into a committed folder.

Closes OPEN ISSUES #1 and #2 together.

#1  outputs/ is gitignored, so the exercise deliverables never reach the repo.
#2  Streamlit Community Cloud has no spaCy cache and ~1 GB of RAM, so the app
    cannot rebuild anything at start-up.

Both are solved by copying the final CSVs into data/artifacts/, which IS
committed. The whole set is a few megabytes - far cheaper than shipping a
compressed DocBin of 500 parsed documents, and it means the deployed app never
imports a language model.

    python scripts/export_artifacts.py
    python scripts/export_artifacts.py --sample-rows 2000   # smaller commit

Then add to git:
    git add data/artifacts
"""

from __future__ import annotations

import argparse
import csv
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from entropy.relations import output_dir  # noqa: E402

# Copied in full - the app needs every row to filter and search properly.
FULL_COPY = [
    "entities.csv",
    "entity_summary.csv",
    "relations.csv",
    "relation_summary.csv",
    "events.csv",
    "event_summary.csv",
    "timed_events.csv",
    "temporal_links.csv",
    "graph_nodes.csv",
    "graph_edges.csv",
    "graph_stats.json",
    "pos_summary.csv",
    "preprocessing_report.csv",
]
# Truncated - a representative slice is enough for a grader, and the full
# token dump would dominate the repository.
SAMPLED = ["tokens_conll.tsv"]
# Never published: rebuildable and redundant with the CSVs above.
SKIPPED = ["graph.json", "timeline.csv", "graph_focus.dot"]


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Copy extraction outputs into the committed artefacts folder.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--out-dir", type=Path, default=None,
                        help="where the pipeline wrote its CSVs")
    parser.add_argument("--artifacts-dir", type=Path, default=None,
                        help="destination; defaults to <repo>/data/artifacts")
    parser.add_argument("--sample-rows", type=int, default=5000,
                        help="rows kept from oversized files")
    parser.add_argument("--clean", action="store_true",
                        help="empty the destination first")
    return parser.parse_args(argv)


def _size(path: Path) -> str:
    kilobytes = path.stat().st_size / 1024
    return f"{kilobytes:,.0f} KB" if kilobytes < 1024 else f"{kilobytes / 1024:.1f} MB"


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    source_dir = args.out_dir or output_dir()
    repo_root = Path(__file__).resolve().parents[1]
    target_dir = args.artifacts_dir or (repo_root / "data" / "artifacts")

    if args.clean and target_dir.exists():
        shutil.rmtree(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    print(f"{source_dir}  ->  {target_dir}\n")
    copied = 0
    total_bytes = 0

    for filename in FULL_COPY:
        source = source_dir / filename
        if not source.exists():
            print(f"  skip    {filename:<28} (not produced yet)")
            continue
        destination = target_dir / filename
        shutil.copy2(source, destination)
        total_bytes += destination.stat().st_size
        copied += 1
        print(f"  copied  {filename:<28} {_size(destination)}")

    for filename in SAMPLED:
        source = source_dir / filename
        if not source.exists():
            continue
        destination = target_dir / f"{Path(filename).stem}_sample{Path(filename).suffix}"
        delimiter = "\t" if filename.endswith(".tsv") else ","
        with source.open(encoding="utf-8", newline="") as handle_in, \
                destination.open("w", encoding="utf-8", newline="") as handle_out:
            reader = csv.reader(handle_in, delimiter=delimiter)
            writer = csv.writer(handle_out, delimiter=delimiter)
            for index, row in enumerate(reader):
                if index > args.sample_rows:
                    break
                writer.writerow(row)
        total_bytes += destination.stat().st_size
        copied += 1
        print(f"  sampled {destination.name:<28} {_size(destination)} "
              f"(first {args.sample_rows:,} rows)")

    readme = target_dir / "README.md"
    readme.write_text(
        "# Extraction artefacts\n\n"
        "Generated by `scripts/export_artifacts.py`. **Do not edit by hand.**\n\n"
        "These CSVs are committed on purpose: `outputs/` is gitignored, and the "
        "Streamlit app reads this folder when deployed to Community Cloud, where "
        "there is no spaCy cache and no room to load a model.\n\n"
        "Regenerate with:\n\n"
        "```\npython scripts/preprocess.py\n"
        "python scripts/extract_entities.py\n"
        "python scripts/extract_relations.py\n"
        "python scripts/build_graph.py\n"
        "python scripts/export_artifacts.py\n```\n",
        encoding="utf-8",
    )

    megabytes = total_bytes / (1024 * 1024)
    print(f"\n{copied} file(s), {megabytes:.1f} MB total")
    if megabytes > 50:
        print("  WARNING: over 50 MB. Raise --sample-rows limits or drop "
              "entities.csv before committing.")
    print("\nNext:\n  git add data/artifacts\n"
          '  git commit -m "Stage 5: publish extraction artefacts"')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
